# Basic
title: Bluelich
subtitle: 在成为极客的路上前行
welcome_message: <a href="https://github.com/bluelich" target="_blank">欢迎访问我的Gitbub</a>
description: 一名iOS开发者.
creator: <a href="http://weibo.com/1376767097">@bluelich</a>

url: "http://bluelich.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 进入

# Navigation buttons in the front page.
nav:
    - {title: 微博, description: Bluclih的微博, url: 'http://weibo.com/1376767097'}
    - {title: 关于, description: 关于, url: 'http://bluelich.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
#    disqus: bluelich
    duoshuo: bluelich
    
# Social
social:
    weibo: 1376767097
    github: bluelich
    twitter: hnjyzqq
    gplus: 114319510293662786333
    mail: bluelich@qq.com

# Google Analytics
ga:
    id: UA-78250446-1
    host: http://bluelich.com
